experiments:

# Rispetto al paper delle clique, ci si domanda se una Klxm+1 con chain = m+1 sia embeddabile anche se non native 

#   - id: 1
#     logical_graph: "graphs/K4.txt"
#     logical_graph_json: graphs/K4.json
#     physical_graph: "graphs/zephyr1.txt"
#     physical_graph_json: graphs/zephyr1.json
#     timeout_seconds: 600
#     embedding_constraints:
#       default_allowed_expansions: [1]
#
#   - id: 2
#     logical_graph: "graphs/K8.txt"
#     logical_graph_json: graphs/K8.json
#     physical_graph: "graphs/zephyr1.txt"
#     physical_graph_json: graphs/zephyr1.json
#     timeout_seconds: 600
#     embedding_constraints:
#       default_allowed_expansions: [1]
#
#   - id: 3
#     logical_graph: "graphs/K8,8.txt"
#     logical_graph_json: graphs/K8,8.json
#     physical_graph: "graphs/zephyr1.txt"
#     physical_graph_json: graphs/zephyr1.json
#     timeout_seconds: 600
#     embedding_constraints:
#       default_allowed_expansions: [1]
#   
#   - id: 4
#     logical_graph: "graphs/K17.txt"
#     logical_graph_json: graphs/K17.json
#     physical_graph: "graphs/zephyr1.txt"
#     physical_graph_json: graphs/zephyr1.json
#     timeout_seconds: 600
#     embedding_constraints:
#        default_allowed_expansions: [1,2]
#        per_node:
#         0: [1]
#         1: [1]
#         2: [1]
#         3: [1]
#         4: [1]
#         5: [2]
#         6: [2]
#         7: [2]
#         8: [2]
#         9: [2]
#         10: [2]
#         11: [2]
#         12: [2]
#         13: [2]
#         14: [2]
#         15: [2]
#         16: [2]
#   - id: 5
#     logical_graph: "graphs/K8.txt"
#     logical_graph_json: graphs/K8.json
#     physical_graph: "graphs/zephyr1.txt"
#     physical_graph_json: graphs/zephyr1.json
#     timeout_seconds: 600
#     embedding_constraints:
#        default_allowed_expansions: [1,2]
#        per_node:
#         0: [1]
#         1: [1]
#         2: [1]
#         3: [1]
#         4: [2]
#         5: [2]
#         6: [2]
#         7: [2]
#   - id: 6
#     logical_graph: "graphs/K8.txt"
#     logical_graph_json: graphs/K8.json
#     physical_graph: "graphs/zephyr1.txt"
#     physical_graph_json: graphs/zephyr1.json
#     timeout_seconds: 600
#     embedding_constraints:
#        default_allowed_expansions: [1,2]
#        per_node:
#         0: [1]
#         1: [1]
#         2: [1]
#         3: [1]
#         4: [1]
#         5: [2]
#         6: [2]
#         7: [2]
#   - id: 7
#     logical_graph: "graphs/K7.txt"
#     logical_graph_json: graphs/K7.json
#     physical_graph: "graphs/zephyr1.txt"
#     physical_graph_json: graphs/zephyr1.json
#     timeout_seconds: 600
#     embedding_constraints:
#        default_allowed_expansions: [1]
#   - id: 8
#     logical_graph: "graphs/K33.txt"
#     logical_graph_json: graphs/K33.json
#     physical_graph: "graphs/zephyr2.txt"
#     physical_graph_json: graphs/zephyr2.json
#     timeout_seconds: 600
#     embedding_constraints:
#        default_allowed_expansions: [1]

#   - id: 9
#     logical_graph: "graphs/chimera1,1,4.txt"
#     logical_graph_json: graphs/chimera1,1,4.json
#     physical_graph: "graphs/zephyr1.txt"
#     physical_graph_json: graphs/zephyr1.json
#     timeout_seconds: 600
#     embedding_constraints:
#      default_allowed_expansions: [1]
#
    - id: 10
      logical_graph: "graphs/K3.txt"
      logical_graph_json: graphs/K5.json
      physical_graph: "graphs/zephyr1.txt"
      physical_graph_json: graphs/zephyr1.json
      timeout_seconds: 600
      embedding_constraints:
       default_allowed_expansions: [1,2,3]



